# Generated by Django 3.0.3 on 2021-01-09 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='summaries')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, max_length=3000)),
                ('from_police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_police', to=settings.AUTH_USER_MODEL)),
                ('on_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Admin_Rate', models.PositiveSmallIntegerField(choices=[(1, '1 - Under Average'), (2, '2 - Average'), (3, '3 - Great'), (4, '4 - Awesome'), (5, '4 - Master')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='teacher', max_length=300, null=True)),
                ('Profile_pic', models.ImageField(default='default2.jpg', upload_to='profile_pic')),
                ('description', models.TextField(blank=True, null=True)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Famale')], max_length=300, null=True)),
                ('cv', models.FileField(upload_to='cv')),
                ('undergraduate', models.CharField(choices=[('BA', 'Bachelor'), ('BSc', 'Bachelor of Science'), ('MA', 'Master'), ('MSc', 'Master of Science'), ('PhD', 'Doctor of Philosophy')], max_length=300, null=True)),
                ('followed_by', models.ManyToManyField(related_name='followed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Admin_Rate', models.PositiveSmallIntegerField(choices=[(1, '1 - Under Average'), (2, '2 - Average'), (3, '3 - Great'), (4, '4 - Awesome'), (5, '4 - Master')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=300, null=True)),
                ('Profile_pic', models.ImageField(default='default.gif', upload_to='profile_pic')),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Famale')], max_length=300, null=True)),
                ('location', models.CharField(max_length=20)),
                ('study_choice', models.CharField(choices=[('aerospace engineering', 'Aerospace Engineering'), ('architecture', 'Architecture'), ('business', 'Business'), ('chemical engineering', 'Chemical Engineering'), ('civil engineering', 'Civil Engineering'), ('computer engineering', 'Computer Engineering'), ('computer science', 'Computer Science'), ('economics', 'Economics'), ('education', 'Education'), ('electrical engineering', 'Electrical Engineering'), ('engineering', 'Engineering'), ('graphic design', 'Graphic Design'), ('industrial engineering', 'Industrial Engineering'), ('software engineering', 'Software Engineering')], max_length=300, null=True)),
                ('years_in_academy', models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate')], max_length=300, null=True)),
                ('Followed_On', models.ManyToManyField(to='accounts.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(blank=True, max_length=3000)),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, '1 - Kill Him'), (2, '2 - Send to Hadas'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Perfect')])),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
